#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-gegl-0.3
Version  : 0.3.28
Release  : 4
URL      : https://download.gimp.org/pub/gegl/0.3/gegl-0.3.28.tar.bz2
Source0  : https://download.gimp.org/pub/gegl/0.3/gegl-0.3.28.tar.bz2
Summary  : Generic Graphics Library
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 LGPL-3.0
Requires: compat-gegl-0.3-bin
Requires: compat-gegl-0.3-lib
Requires: compat-gegl-0.3-data
Requires: compat-gegl-0.3-locales
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : graphviz
BuildRequires : lcms2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(babl)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(exiv2)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gexiv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(lensfun)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libraw)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(lua)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(pygobject-3.0)
BuildRequires : python
BuildRequires : ruby-dev

%description
GEGL-0.3.28
GEGL
GEGL
GEGL (Generic Graphics Library) is a data flow based image processing
framework, providing floating point processing and non-destructive
image processing capabilities to GNU Image Manipulation Program and
other projects (imgflo, GNOME Photos, gcut, iconographer, â¦)

%package bin
Summary: bin components for the compat-gegl-0.3 package.
Group: Binaries
Requires: compat-gegl-0.3-data

%description bin
bin components for the compat-gegl-0.3 package.


%package data
Summary: data components for the compat-gegl-0.3 package.
Group: Data

%description data
data components for the compat-gegl-0.3 package.


%package dev
Summary: dev components for the compat-gegl-0.3 package.
Group: Development
Requires: compat-gegl-0.3-lib
Requires: compat-gegl-0.3-bin
Requires: compat-gegl-0.3-data
Provides: compat-gegl-0.3-devel

%description dev
dev components for the compat-gegl-0.3 package.


%package lib
Summary: lib components for the compat-gegl-0.3 package.
Group: Libraries
Requires: compat-gegl-0.3-data

%description lib
lib components for the compat-gegl-0.3 package.


%package locales
Summary: locales components for the compat-gegl-0.3 package.
Group: Default

%description locales
locales components for the compat-gegl-0.3 package.


%prep
%setup -q -n gegl-0.3.28

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1524866875
%configure --disable-static --without-jasper --without-tiff --disable-docs PYTHON=/usr/bin/python3 --without-vala
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1524866875
rm -rf %{buildroot}
%make_install
%find_lang gegl-0.3

%files
%defattr(-,root,root,-)
/usr/lib64/gegl-0.3/grey2.json

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/gcut
%exclude /usr/bin/gegl
%exclude /usr/bin/gegl-imgcmp

%files data
%defattr(-,root,root,-)
%exclude /usr/lib64/girepository-1.0/Gegl-0.3.typelib
%exclude /usr/share/gir-1.0/Gegl-0.3.gir

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/gegl-0.3/gegl-apply.h
%exclude /usr/include/gegl-0.3/gegl-audio-fragment.h
%exclude /usr/include/gegl-0.3/gegl-buffer-backend.h
%exclude /usr/include/gegl-0.3/gegl-buffer-cl-iterator.h
%exclude /usr/include/gegl-0.3/gegl-buffer-iterator.h
%exclude /usr/include/gegl-0.3/gegl-buffer.h
%exclude /usr/include/gegl-0.3/gegl-color.h
%exclude /usr/include/gegl-0.3/gegl-cpuaccel.h
%exclude /usr/include/gegl-0.3/gegl-curve.h
%exclude /usr/include/gegl-0.3/gegl-debug.h
%exclude /usr/include/gegl-0.3/gegl-enums.h
%exclude /usr/include/gegl-0.3/gegl-graph-debug.h
%exclude /usr/include/gegl-0.3/gegl-init.h
%exclude /usr/include/gegl-0.3/gegl-lookup.h
%exclude /usr/include/gegl-0.3/gegl-matrix.h
%exclude /usr/include/gegl-0.3/gegl-node.h
%exclude /usr/include/gegl-0.3/gegl-op.h
%exclude /usr/include/gegl-0.3/gegl-operations-util.h
%exclude /usr/include/gegl-0.3/gegl-paramspecs.h
%exclude /usr/include/gegl-0.3/gegl-path.h
%exclude /usr/include/gegl-0.3/gegl-plugin.h
%exclude /usr/include/gegl-0.3/gegl-processor.h
%exclude /usr/include/gegl-0.3/gegl-random.h
%exclude /usr/include/gegl-0.3/gegl-tile-backend.h
%exclude /usr/include/gegl-0.3/gegl-tile-handler.h
%exclude /usr/include/gegl-0.3/gegl-tile-source.h
%exclude /usr/include/gegl-0.3/gegl-tile.h
%exclude /usr/include/gegl-0.3/gegl-types.h
%exclude /usr/include/gegl-0.3/gegl-utils.h
%exclude /usr/include/gegl-0.3/gegl-version.h
%exclude /usr/include/gegl-0.3/gegl.h
%exclude /usr/include/gegl-0.3/npd/deformation.h
%exclude /usr/include/gegl-0.3/npd/graphics.h
%exclude /usr/include/gegl-0.3/npd/lattice_cut.h
%exclude /usr/include/gegl-0.3/npd/npd.h
%exclude /usr/include/gegl-0.3/npd/npd_common.h
%exclude /usr/include/gegl-0.3/npd/npd_debug.h
%exclude /usr/include/gegl-0.3/npd/npd_gegl.h
%exclude /usr/include/gegl-0.3/npd/npd_math.h
%exclude /usr/include/gegl-0.3/opencl/cl.h
%exclude /usr/include/gegl-0.3/opencl/cl_d3d10.h
%exclude /usr/include/gegl-0.3/opencl/cl_ext.h
%exclude /usr/include/gegl-0.3/opencl/cl_gl.h
%exclude /usr/include/gegl-0.3/opencl/cl_gl_ext.h
%exclude /usr/include/gegl-0.3/opencl/cl_platform.h
%exclude /usr/include/gegl-0.3/opencl/gegl-cl-color.h
%exclude /usr/include/gegl-0.3/opencl/gegl-cl-init.h
%exclude /usr/include/gegl-0.3/opencl/gegl-cl-random.h
%exclude /usr/include/gegl-0.3/opencl/gegl-cl-types.h
%exclude /usr/include/gegl-0.3/opencl/gegl-cl.h
%exclude /usr/include/gegl-0.3/opencl/opencl.h
%exclude /usr/include/gegl-0.3/operation/gegl-extension-handler.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-area-filter.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-composer.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-composer3.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-context.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-filter.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-handlers.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-meta-json.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-meta.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-point-composer.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-point-composer3.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-point-filter.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-point-render.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-property-keys.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-sink.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-source.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation-temporal.h
%exclude /usr/include/gegl-0.3/operation/gegl-operation.h
%exclude /usr/include/gegl-0.3/sc/sc-common.h
%exclude /usr/include/gegl-0.3/sc/sc-context.h
%exclude /usr/include/gegl-0.3/sc/sc-outline.h
%exclude /usr/include/gegl-0.3/sc/sc-sample.h
%exclude /usr/lib64/libgegl-0.3.so
%exclude /usr/lib64/libgegl-npd-0.3.so
%exclude /usr/lib64/libgegl-sc-0.3.so
%exclude /usr/lib64/pkgconfig/gegl-0.3.pc
%exclude /usr/lib64/pkgconfig/gegl-sc-0.3.pc

%files lib
%defattr(-,root,root,-)
%exclude /usr/lib64/gegl-0.3/gegl-common-gpl3.so
%exclude /usr/lib64/gegl-0.3/gegl-common.so
%exclude /usr/lib64/gegl-0.3/gegl-core.so
%exclude /usr/lib64/gegl-0.3/gegl-generated.so
%exclude /usr/lib64/gegl-0.3/jpg-load.so
%exclude /usr/lib64/gegl-0.3/jpg-save.so
%exclude /usr/lib64/gegl-0.3/lcms-from-profile.so
%exclude /usr/lib64/gegl-0.3/npd.so
%exclude /usr/lib64/gegl-0.3/npy-save.so
%exclude /usr/lib64/gegl-0.3/path.so
%exclude /usr/lib64/gegl-0.3/pixbuf.so
%exclude /usr/lib64/gegl-0.3/png-load.so
%exclude /usr/lib64/gegl-0.3/png-save.so
%exclude /usr/lib64/gegl-0.3/ppm-load.so
%exclude /usr/lib64/gegl-0.3/ppm-save.so
%exclude /usr/lib64/gegl-0.3/raw-load.so
%exclude /usr/lib64/gegl-0.3/rgbe-load.so
%exclude /usr/lib64/gegl-0.3/rgbe-save.so
%exclude /usr/lib64/gegl-0.3/save-pixbuf.so
%exclude /usr/lib64/gegl-0.3/seamless-clone-compose.so
%exclude /usr/lib64/gegl-0.3/seamless-clone.so
%exclude /usr/lib64/gegl-0.3/svg-load.so
%exclude /usr/lib64/gegl-0.3/text.so
%exclude /usr/lib64/gegl-0.3/transformops.so
%exclude /usr/lib64/gegl-0.3/v4l.so
%exclude /usr/lib64/gegl-0.3/vector-fill.so
%exclude /usr/lib64/gegl-0.3/vector-stroke.so
/usr/lib64/libgegl-0.3.so.0
/usr/lib64/libgegl-0.3.so.0.328.0

%files locales -f gegl-0.3.lang
%defattr(-,root,root,-)

