#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-gegl-0.3
Version  : 0.3.28
Release  : 14
URL      : https://download.gimp.org/pub/gegl/0.3/gegl-0.3.28.tar.bz2
Source0  : https://download.gimp.org/pub/gegl/0.3/gegl-0.3.28.tar.bz2
Summary  : Generic Graphics Library
Group    : Development/Tools
License  : BSD-3-Clause GPL-3.0 LGPL-3.0
Requires: compat-gegl-0.3-lib = %{version}-%{release}
Requires: compat-gegl-0.3-license = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gettext-bin
BuildRequires : gobject-introspection-dev
BuildRequires : graphviz
BuildRequires : lcms2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libxslt-bin
BuildRequires : m4
BuildRequires : openexr-dev
BuildRequires : perl
BuildRequires : perl(XML::Parser)
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(babl)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(exiv2)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gexiv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(lensfun)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libraw)
BuildRequires : pkgconfig(librsvg-2.0)
BuildRequires : pkgconfig(libv4l2)
BuildRequires : pkgconfig(lua)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(pygobject-3.0)
BuildRequires : python
BuildRequires : ruby-dev
BuildRequires : tiff-dev
# Suppress generation of debuginfo
%global debug_package %{nil}
Patch1: 0001-Disable-content-not-needed-for-compat-libs.patch

%description
GEGL-0.3.28
GEGL
GEGL
GEGL (Generic Graphics Library) is a data flow based image processing
framework, providing floating point processing and non-destructive
image processing capabilities to GNU Image Manipulation Program and
other projects (imgflo, GNOME Photos, gcut, iconographer, …)

%package lib
Summary: lib components for the compat-gegl-0.3 package.
Group: Libraries
Requires: compat-gegl-0.3-license = %{version}-%{release}

%description lib
lib components for the compat-gegl-0.3 package.


%package license
Summary: license components for the compat-gegl-0.3 package.
Group: Default

%description license
license components for the compat-gegl-0.3 package.


%prep
%setup -q -n gegl-0.3.28
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568050039
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%reconfigure --disable-static --without-jasper --without-tiff --disable-docs PYTHON=/usr/bin/python3 --without-vala
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1568050039
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-gegl-0.3
cp COPYING %{buildroot}/usr/share/package-licenses/compat-gegl-0.3/COPYING
cp COPYING.LESSER %{buildroot}/usr/share/package-licenses/compat-gegl-0.3/COPYING.LESSER
cp libs/poly2tri-c/COPYING %{buildroot}/usr/share/package-licenses/compat-gegl-0.3/libs_poly2tri-c_COPYING
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/bin/gcut
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-apply.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-audio-fragment.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-buffer-backend.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-buffer-cl-iterator.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-buffer-iterator.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-buffer.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-color.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-cpuaccel.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-curve.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-debug.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-enums.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-graph-debug.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-init.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-lookup.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-matrix.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-node.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-op.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-operations-util.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-paramspecs.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-path.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-plugin.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-processor.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-random.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-tile-backend.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-tile-handler.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-tile-source.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-tile.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-types.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-utils.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl-version.h
rm -f %{buildroot}/usr/include/gegl-0.3/gegl.h
rm -f %{buildroot}/usr/include/gegl-0.3/npd/deformation.h
rm -f %{buildroot}/usr/include/gegl-0.3/npd/graphics.h
rm -f %{buildroot}/usr/include/gegl-0.3/npd/lattice_cut.h
rm -f %{buildroot}/usr/include/gegl-0.3/npd/npd.h
rm -f %{buildroot}/usr/include/gegl-0.3/npd/npd_common.h
rm -f %{buildroot}/usr/include/gegl-0.3/npd/npd_debug.h
rm -f %{buildroot}/usr/include/gegl-0.3/npd/npd_gegl.h
rm -f %{buildroot}/usr/include/gegl-0.3/npd/npd_math.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/cl.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/cl_d3d10.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/cl_ext.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/cl_gl.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/cl_gl_ext.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/cl_platform.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/gegl-cl-color.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/gegl-cl-init.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/gegl-cl-random.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/gegl-cl-types.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/gegl-cl.h
rm -f %{buildroot}/usr/include/gegl-0.3/opencl/opencl.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-extension-handler.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-area-filter.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-composer.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-composer3.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-context.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-filter.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-handlers.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-meta-json.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-meta.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-point-composer.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-point-composer3.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-point-filter.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-point-render.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-property-keys.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-sink.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-source.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation-temporal.h
rm -f %{buildroot}/usr/include/gegl-0.3/operation/gegl-operation.h
rm -f %{buildroot}/usr/include/gegl-0.3/sc/sc-common.h
rm -f %{buildroot}/usr/include/gegl-0.3/sc/sc-context.h
rm -f %{buildroot}/usr/include/gegl-0.3/sc/sc-outline.h
rm -f %{buildroot}/usr/include/gegl-0.3/sc/sc-sample.h
rm -f %{buildroot}/usr/lib64/gegl-0.3/exr-load.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/exr-save.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/gegl-common-gpl3.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/gegl-common.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/gegl-core.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/gegl-generated.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/jpg-load.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/jpg-save.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/lcms-from-profile.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/npd.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/npy-save.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/path.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/pixbuf.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/png-load.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/png-save.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/ppm-load.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/ppm-save.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/raw-load.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/rgbe-load.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/rgbe-save.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/save-pixbuf.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/seamless-clone-compose.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/seamless-clone.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/svg-load.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/text.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/tiff-load.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/tiff-save.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/transformops.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/v4l.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/vector-fill.so
rm -f %{buildroot}/usr/lib64/gegl-0.3/vector-stroke.so
rm -f %{buildroot}/usr/lib64/girepository-1.0/Gegl-0.3.typelib
rm -f %{buildroot}/usr/lib64/libgegl-0.3.so
rm -f %{buildroot}/usr/lib64/libgegl-npd-0.3.so
rm -f %{buildroot}/usr/lib64/libgegl-sc-0.3.so
rm -f %{buildroot}/usr/lib64/pkgconfig/gegl-0.3.pc
rm -f %{buildroot}/usr/lib64/pkgconfig/gegl-sc-0.3.pc
rm -f %{buildroot}/usr/share/gir-1.0/Gegl-0.3.gir

%files
%defattr(-,root,root,-)
/usr/lib64/gegl-0.3/grey2.json

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgegl-0.3.so.0
/usr/lib64/libgegl-0.3.so.0.328.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-gegl-0.3/COPYING
/usr/share/package-licenses/compat-gegl-0.3/COPYING.LESSER
/usr/share/package-licenses/compat-gegl-0.3/libs_poly2tri-c_COPYING
